const INITIALIZE_VEHICLES="INITIALIZE_VEHICLES";
const INITIALIZE_VEHICLES_SELECTED="INITIALIZE_VEHICLES_SELECTED";
const INITIALIZE_PLANETS="INITIALIZE_PLANETS";
const INITIALIZE_PLANETS_SELECTED="INITIALIZE_PLANETS_SELECTED";
const UPDATE_FINAL_ARRAY="UPDATE_FINAL_ARRAY";
const GET_RESULT="GET_RESULT";
const RESET="RESET";

module.exports = { INITIALIZE_VEHICLES,
                   INITIALIZE_VEHICLES_SELECTED,
                   INITIALIZE_PLANETS,
                   INITIALIZE_PLANETS_SELECTED,
                   UPDATE_FINAL_ARRAY,
                   GET_RESULT,
                   RESET };

